import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "../common/Button";
import Card from "../common/Card";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/*  eslint-disable-next-line @next/next/no-html-link-for-pages */}
          Welcome to <a href="/">App With No Name!</a>
        </h1>
        <Card>
          <Link href="/login" passHref>
            <Button as="a">Login page</Button>
          </Link>
          <Link href="/register" passHref>
            <Button as="a">Register page</Button>
          </Link>
        </Card>
      </main>
    </div>
  );
};

export default Home;
